USE [master]
GO

/****** Object:  Database [AutoServiceSystemPro]    Script Date: 10/31/2021 8:36:26 AM ******/
DROP DATABASE [AutoServiceSystemPro]
GO

/****** Object:  Database [AutoServiceSystemPro]    Script Date: 10/31/2021 8:36:26 AM ******/
CREATE DATABASE [AutoServiceSystemPro]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AutoServiceSystemPro', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AutoServiceSystemPro.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AutoServiceSystemPro_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AutoServiceSystemPro_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AutoServiceSystemPro].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AutoServiceSystemPro] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AutoServiceSystemPro] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AutoServiceSystemPro] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AutoServiceSystemPro] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AutoServiceSystemPro] SET ARITHABORT OFF 
GO

ALTER DATABASE [AutoServiceSystemPro] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AutoServiceSystemPro] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AutoServiceSystemPro] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AutoServiceSystemPro] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AutoServiceSystemPro] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AutoServiceSystemPro] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AutoServiceSystemPro] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AutoServiceSystemPro] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AutoServiceSystemPro] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AutoServiceSystemPro] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AutoServiceSystemPro] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AutoServiceSystemPro] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AutoServiceSystemPro] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AutoServiceSystemPro] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AutoServiceSystemPro] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AutoServiceSystemPro] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AutoServiceSystemPro] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AutoServiceSystemPro] SET RECOVERY FULL 
GO

ALTER DATABASE [AutoServiceSystemPro] SET  MULTI_USER 
GO

ALTER DATABASE [AutoServiceSystemPro] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AutoServiceSystemPro] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AutoServiceSystemPro] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AutoServiceSystemPro] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AutoServiceSystemPro] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AutoServiceSystemPro] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [AutoServiceSystemPro] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AutoServiceSystemPro] SET  READ_WRITE 
GO


